version: '3'
services:
  # Define the Node.js service
  app:
    build: .
    image: ${DOCKERHUB_USERNAME}/node_app:latest
    container_name: node_app
    ports:
      - '3000:3000' # Expose port 3000 of the container to port 3000 of your machine
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://127.0.0.1:27017/dockersample # Update to match your MongoDB URL

  # Define the MongoDB service
  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

  # Define the Mongo Express service
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    depends_on:
      - mongo
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

# Define volumes for persistent storage
volumes:
  mongo_data:
